=begin
muggles-waffles

CS 5150 Navigation in Library Stacks.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :message
      t.string :fields

      t.timestamps
    end

    create_table "floor".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name
      t.decimal :size_x
      t.decimal :size_y
      t.string :geojson
      t.integer :library

      t.timestamps
    end

    create_table "library".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name
      t.decimal :latitude
      t.decimal :longitude

      t.timestamps
    end

    create_table "rule".pluralize.to_sym, id: false do |t|
      t.string :rule_type
      t.integer :rule_id
      t.string :call_number
      t.string :rule

      t.timestamps
    end

    create_table "search_result".pluralize.to_sym, id: false do |t|
      t.string :result_type
      t.integer :result_id
      t.string :result

      t.timestamps
    end

    create_table "stack".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.decimal :cx
      t.decimal :cy
      t.decimal :lx
      t.decimal :ly
      t.decimal :rotation
      t.string :geojson
      t.string :start_class
      t.integer :start_subclass
      t.string :end_class
      t.integer :end_subclass
      t.integer :oversize
      t.integer :floor

      t.timestamps
    end

  end
end
