# waffles-muggles
#
# CS 5150 Navigation in Library Stacks.
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#
class LibrariesController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:create]

    def index
        ret = []
        Library.all.each do |library|
            ret << {
                id: library.id,
                name: library.name,
                latitude: library.latitude,
                longitude: library.longitude
            }
        end
        render json: ret
    end

    def destroy
        Library.find(params[:id]).destroy
        render json: 'OK'.to_json
    end

    def create
        library = Library.new
        library.name = params[:name]
        library.latitude = params[:latitude]
        library.longitude = params[:longitude]
        library.save
        render json: library.id.to_json
    end

    def libraries_put
        library = Library.find(params[:id])
        library.name = params[:name]
        library.latitude = params[:latitude]
        library.longitude = params[:longitude]
        library.save
        render json: 'OK'.to_json
    end
end
