# waffles-muggles
#
# CS 5150 Navigation in Library Stacks.
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#
class RulesController < ApplicationController
    def index
        ret = []
        Rule.find_each do |rule|
            ret << {
                rule_type: rule.rule_type,
                rule_id: rule.rule_id,
                call_number: rule.call_number,
                rule: rule.rule
            }
        end
        render json: ret
    end

    def destroy
        Rule.find(params[:id]).destroy
        render json: 'OK'.to_json
    end

    def create
        rule = Rule.new
        rule.rule_type = params[:rule_type]
        rule.rule_id = params[:rule_id]
        rule.call_number = params[:call_number]
        rule.rule = params[:rule]
        rule.save
        render json: rule.id.to_json
    end
end
