# waffles-muggles
#
# CS 5150 Navigation in Library Stacks.
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#
class SearchController < ApplicationController
    def index
        re = /([A-z]{1,3})(\d+(?:\.[A-z]*\d+)*)\s+\.?([A-z])(\d+)\s+([^+]*)([+]*)/
        callno_dec = re.match(params[:keyword])
        oversize = callno_dec[6].length
        rules = []
        Rule.find_each do |rule|
            rules << rule if rule.call_number == callno_dec[0]
        end

        if !rules.empty?
            ret = []
            rules.each do |rule|
                ret << {
                    result_type: rule.rule_type,
                    result_id: rule.rule_id,
                    result: [rule.call_number, rule.rule].join(', ')
                }
            end
            render json: ret
        else
            render json: classSearch(callno_dec[1], callno_dec[2].split('.')[0], oversize)
        end
    end

    def classSearch(class_code, subclass, oversize)
        ret = []
        subclass = subclass.to_i
        Stack.find_each do |stack|
            if stack.oversize == oversize &&
               (stack.start_class < class_code ||
               (stack.start_class == class_code && stack.start_subclass <= subclass)) &&
               (stack.end_class > class_code ||
               (stack.end_class == class_code && stack.end_subclass >= subclass))
                ret << {
                    result_type: 'Stack',
                    result_id: stack.id,
                    result: [stack.start_class, stack.start_subclass, stack.end_class, stack.end_subclass, stack.oversize].join(', ')
                }
            end
        end
        ret
    end
end
