=begin
muggles-waffles

CS 5150 Navigation in Library Stacks.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SearchController < ApplicationController

  def index
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
