# waffles-muggles
#
# CS 5150 Navigation in Library Stacks.
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#
class StacksController < ApplicationController
    include ApplicationControllerConcern

    def index
        ret = []
        Stack.find_each do |stack|
            ret << getStack(stack) if stack.floor == params[:floor_id].to_i
        end
        render json: ret
    end

    def destroy
        Stack.find(params[:id]).destroy
        render json: 'OK'.to_json
    end

    def show
        render json: getStackById(params[:id])
    end

    def create
        stack = Stack.new
        stack.cx = params[:cx]
        stack.cy = params[:cy]
        stack.lx = params[:lx]
        stack.ly = params[:ly]
        stack.rotation = params[:rotation] ? params[:rotation] : 0
        stack.geojson = params[:geojson]
        stack.start_class = params[:startClass]
        stack.start_subclass = params[:startSubclass] ? params[:startSubclass] : 0
        stack.end_class = params[:endClass]
        stack.end_subclass = params[:endSubclass]
        stack.oversize = params[:oversize] ? params[:oversize] : 0
        stack.floor = params[:floor]
        stack.save
        render json: 'OK'.to_json
    end

    def stacks_put
        stack = Stack.find(params[:id])
        stack.cx = params[:cx]
        stack.cy = params[:cy]
        stack.lx = params[:lx]
        stack.ly = params[:ly]
        stack.rotation = params[:rotation] ? params[:rotation] : 0
        stack.geojson = params[:geojson]
        stack.start_class = params[:startClass]
        stack.start_subclass = params[:startSubclass] ? params[:startSubclass] : 0
        stack.end_class = params[:endClass]
        stack.end_subclass = params[:endSubclass]
        stack.oversize = params[:oversize] ? params[:oversize] : 0
        stack.floor = params[:floor]
        stack.save
        render json: 'OK'.to_json
    end
end
