=begin
muggles-waffles

CS 5150 Navigation in Library Stacks.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Error < ApplicationRecord

end
